### PR TITLE
Fixed debug

### PR DESCRIPTION
**Pull request by wyatt-herkamp**
Fixed the Debug Screen.

### CODE REVIEW

**Comment by jaythomas** [comment]
Do we need the debug.lua file at this point? Can all that debug OSD just exist in the DebugPlayer system?

**Comment by wyatt-herkamp** [comment]
> Do we need the debug.lua file at this point? Can all that debug OSD just exist in the DebugPlayer system?

I don't really know Lua and it had gotten mad when I tried to put the files together. This is the first time I have really even looked at Lua.

**Comment by jaythomas** [comment]
My suggestion would be to take the body of your function in debug.lua and move it directly into the system then you can delete debug.lua. Less files and less code. Keeping it simple.

**Comment by wyatt-herkamp** [comment]
@jaythomas I merged the files. I am still keeping them separated by functions to keep the code easy to read.

**Review by jaythomas — APPROVED** [review]

**Pull request merged**
